version: '3'

services:
  web:
    image: phpexperts/web:nginx-php7.4-debug
    depends_on:
      - db
      - redis
    links:
      - db
    volumes:
      - .:/var/www:delegated
      - ./docker/web:/etc/nginx/custom:delegated
    ports:
      - 80:80

  horizon:
    image: phpexperts/web:nginx-php7.4-debug
    command: php artisan horizon
    depends_on:
      - db
    volumes:
      - .:/var/www:delegated

  db:
    image: postgres:12.2
    volumes:
      - /var/lib/docker/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: survivor
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: covidreporter

  redis:
    image: redis:3.2.6
    entrypoint:
      - redis-server
      - --requirepass {REDIS_PASSWORD}
      - --loglevel notice
